# Generated by Django 6.0.3 on 2026-03-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0002_userprofile_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_name',
        ),
    ]
